// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkXmNS35O9eWPLfyDzEJ6wB_JmE13c9Vo',
    appId: '1:970879388773:web:76b2b4882e5759b0a3ca8c',
    messagingSenderId: '970879388773',
    projectId: 'mosanada-app',
    authDomain: 'mosanada-app.firebaseapp.com',
    storageBucket: 'mosanada-app.appspot.com',
    measurementId: 'G-8X7Y8CK05M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTUanr5jR8WNvKHa9AR2xZJq0R-67xRg',
    appId: '1:970879388773:android:e7dfa0bd6d519d09a3ca8c',
    messagingSenderId: '970879388773',
    projectId: 'mosanada-app',
    storageBucket: 'mosanada-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSGrfwDwskp0jTi_WSOqE26phWqG9DmiY',
    appId: '1:970879388773:ios:7d9a0a20e312dc2da3ca8c',
    messagingSenderId: '970879388773',
    projectId: 'mosanada-app',
    storageBucket: 'mosanada-app.appspot.com',
    iosBundleId: 'com.example.mosanadah2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSGrfwDwskp0jTi_WSOqE26phWqG9DmiY',
    appId: '1:970879388773:ios:7d9a0a20e312dc2da3ca8c',
    messagingSenderId: '970879388773',
    projectId: 'mosanada-app',
    storageBucket: 'mosanada-app.appspot.com',
    iosBundleId: 'com.example.mosanadah2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkXmNS35O9eWPLfyDzEJ6wB_JmE13c9Vo',
    appId: '1:970879388773:web:963b071c034f71cca3ca8c',
    messagingSenderId: '970879388773',
    projectId: 'mosanada-app',
    authDomain: 'mosanada-app.firebaseapp.com',
    storageBucket: 'mosanada-app.appspot.com',
    measurementId: 'G-ZLGSH1GN1X',
  );

}